import Link from 'next/link';
import { ArrowRight, Home, PlugZap, ShoppingBasket, Siren, WalletCards } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Reveal } from '@/components/marketing/motion-reveal';

const moments = [
  { title: 'Need food this month?', body: 'Start with SNAP and official state application paths.', icon: ShoppingBasket, prompt: 'I need help buying food this month. What official benefits should I check?' },
  { title: 'Behind on rent?', body: 'Find housing assistance, local agencies, and safer next steps.', icon: Home, prompt: 'I am behind on rent. Where can I find official rental assistance?' },
  { title: 'Utility shutoff risk?', body: 'Check LIHEAP and energy assistance resources.', icon: PlugZap, prompt: 'My utility bill is overdue. Is there official energy assistance?' },
  { title: 'Lost income?', body: 'Explore public benefit finders and emergency support options.', icon: WalletCards, prompt: 'I lost income recently. What public benefits should I look into first?' },
  { title: 'Immediate danger?', body: 'CivicShield points you back to official emergency channels.', icon: Siren, prompt: 'I need emergency help. What official contacts should I use?' }
];

function ImpactVisual() {
  return <div className="relative min-h-[300px] overflow-hidden rounded-[1.5rem] bg-[radial-gradient(circle_at_25%_20%,rgba(59,130,246,0.35),transparent_28%),radial-gradient(circle_at_75%_25%,rgba(16,185,129,0.28),transparent_25%),linear-gradient(135deg,#0f172a,#1d4ed8,#065f46)] p-6"><div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.08)_1px,transparent_1px)] bg-[size:36px_36px] opacity-40" /><div className="relative grid h-full grid-cols-2 gap-4"><div className="rounded-3xl bg-white/15 p-5 text-white backdrop-blur-xl"><ShoppingBasket className="h-8 w-8" /><p className="mt-5 text-sm font-bold">Food support</p></div><div className="rounded-3xl bg-white/15 p-5 text-white backdrop-blur-xl"><Home className="h-8 w-8" /><p className="mt-5 text-sm font-bold">Housing help</p></div><div className="rounded-3xl bg-white/15 p-5 text-white backdrop-blur-xl"><PlugZap className="h-8 w-8" /><p className="mt-5 text-sm font-bold">Utility aid</p></div><div className="rounded-3xl bg-white/15 p-5 text-white backdrop-blur-xl"><Siren className="h-8 w-8" /><p className="mt-5 text-sm font-bold">Emergency paths</p></div></div></div>;
}

export function ImpactSection() {
  return <section id="impact" className="relative overflow-hidden px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.92fr_1.08fr] lg:items-center"><Reveal><div><p className="text-sm font-black uppercase tracking-[0.22em] text-emerald-600 dark:text-emerald-300">Social impact</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 dark:text-white sm:text-5xl">Built for moments when forms, agencies, and deadlines feel overwhelming.</h2><p className="mt-5 text-base leading-8 text-slate-600 dark:text-slate-300">People do not need another confusing portal. They need plain language, official links, and a system that admits uncertainty instead of inventing answers.</p><div className="mt-7 overflow-hidden rounded-[2rem] border border-white/70 bg-white/75 p-3 shadow-[0_24px_80px_rgba(15,23,42,0.12)] backdrop-blur-2xl dark:border-white/10 dark:bg-slate-950/65"><ImpactVisual /></div></div></Reveal><div className="grid gap-4 sm:grid-cols-2">{moments.map((moment, index) => { const Icon = moment.icon; return <Reveal key={moment.title} delay={index * 0.04}><Card className="group h-full p-5 transition duration-300 hover:-translate-y-1 hover:shadow-[0_26px_80px_rgba(37,99,235,0.14)]"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-emerald-500 text-white shadow-lg shadow-blue-500/20"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-bold tracking-[-0.035em] text-slate-950 dark:text-white">{moment.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{moment.body}</p><Link href={`/app?prompt=${encodeURIComponent(moment.prompt)}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-600 transition group-hover:gap-3 dark:text-blue-300">Get next steps <ArrowRight className="h-4 w-4" /></Link></Card></Reveal>; })}</div></div></section>;
}
