import { AlertTriangle, CheckCircle2, Eye, FileCheck2, Scale, ShieldQuestion } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Reveal } from '@/components/marketing/motion-reveal';

const checks = [
  { title: 'Checks trusted sources first', body: 'Answers begin with approved official sources and citation-aware retrieval instead of open-ended guessing.', icon: FileCheck2 },
  { title: 'Shows confidence, not false certainty', body: 'Every response is labeled so users know when to verify with an agency.', icon: ShieldQuestion },
  { title: 'Refuses unsupported answers', body: 'If official evidence is weak, the assistant is designed to refuse unsupported certainty and direct people back to official channels.', icon: AlertTriangle },
  { title: 'Keeps review trails visible', body: 'Reviewer queues and audit logs help teams inspect low-confidence conversations.', icon: Eye }
];

export function TrustShowcase() {
  return <section id="trust" className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><Reveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[0.22em] text-blue-600 dark:text-blue-300">Responsible AI</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 dark:text-white sm:text-5xl">A trust layer for civic information, not just another chatbot.</h2><p className="mt-5 text-base leading-8 text-slate-600 dark:text-slate-300">CivicShield is designed for high-stakes public-service questions where hallucinated benefits, fake deadlines, or wrong agency links can hurt real people.</p></Reveal><div className="mt-10 grid gap-5 lg:grid-cols-4">{checks.map((check, index) => { const Icon = check.icon; return <Reveal key={check.title} delay={index * 0.05}><Card className="h-full p-6 transition duration-300 hover:-translate-y-1 hover:shadow-[0_26px_80px_rgba(15,23,42,0.12)]"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-white dark:bg-white dark:text-slate-950"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-base font-bold tracking-[-0.03em] text-slate-950 dark:text-white">{check.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{check.body}</p></Card></Reveal>; })}</div><Reveal delay={0.12}><Card className="mt-8 overflow-hidden p-0"><div className="grid gap-0 lg:grid-cols-[0.9fr_1.1fr]"><div className="bg-slate-950 p-7 text-white lg:p-9"><div className="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-blue-100">Safe refusal example</div><h3 className="mt-5 text-2xl font-black tracking-[-0.05em]">When evidence is weak, CivicShield says so.</h3><p className="mt-4 text-sm leading-7 text-slate-300">Instead of guessing, the system returns a low-confidence response and guides users back to official sources or emergency channels.</p></div><div className="p-7 lg:p-9"><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/50 dark:bg-amber-950/30"><div className="flex items-start gap-3"><Scale className="mt-1 h-5 w-5 text-amber-600 dark:text-amber-300" /><div><p className="text-sm font-bold text-amber-900 dark:text-amber-100">I cannot confidently verify this information.</p><p className="mt-2 text-sm leading-7 text-amber-800 dark:text-amber-200">The available official evidence is insufficient. Please verify directly with the relevant agency before making a decision.</p></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{['No fabricated links', 'No fake eligibility', 'No hidden certainty'].map((item) => <div key={item} className="flex items-center gap-2 rounded-2xl bg-slate-50 px-3 py-3 text-xs font-bold text-slate-700 dark:bg-slate-900 dark:text-slate-200"><CheckCircle2 className="h-4 w-4 text-emerald-500" /> {item}</div>)}</div></div></div></Card></Reveal></section>;
}
